# Generated by Django 5.0.3 on 2024-03-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_onlineclass_slug_alter_classenrollment_online_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='slug',
        ),
    ]
