# Generated by Django 5.0.3 on 2024-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_onlineclass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
