# Generated by Django 5.0.3 on 2024-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_onlineclass_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
