# Generated by Django 5.0.3 on 2024-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classenrollment_id_alter_onlineclass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
