# Generated by Django 5.0.3 on 2024-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_classenrollment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('Active', 1), ('Cancelled', 0)], default='Active', max_length=50, null=True),
        ),
    ]
