# Generated by Django 5.0.3 on 2024-03-13 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_classmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
