# Generated by Django 5.0.3 on 2024-03-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
