# Generated by Django 5.0.3 on 2024-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='request_delete',
            field=models.BooleanField(default=False),
        ),
    ]
