# Generated by Django 5.0.3 on 2024-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='login_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='token',
            field=models.CharField(default='No-Token', max_length=400),
        ),
    ]
